name: CustomPushedTargets

on: 
  push:
    branches: [main]
    paths:
      - 'target-data/FluID/*'
      - 'target-data/Respivirnet/*'
      - '!**.md'
      - '!**.MD'

jobs:
  custom-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      
      - name: Get changes
        id: changed-files
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }}  ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT


      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
              echo "$file was changed"
          done

       # Save changes to artifact for json db store 
      - name: Save changes to artifact
        env:
          imported_files: ${{ steps.changed-files.outputs.changed_files }}
        run: |
          echo "{ \"pr-changes\" : \"$imported_files\" }" > pr_changes.json
            
      - name: Upload changes
        uses: actions/upload-artifact@v2
        with:
          name: pr_changes
          path: ./pr_changes.json
