name: GenerateEnsemble

on:

  workflow_dispatch:

  workflow_run:
    workflows: [GenerateBaseline]
      
    types:
      - completed


jobs:
  
  ensemble_job:
    # if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'european-modelling-hubs' }}
    runs-on: ubuntu-latest
    outputs:
      changed_files:  ${{ steps.generate_ensemble.outputs.ensemble_file }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # checkout repo
    - uses: actions/checkout@v3
      with: 
        path: './repo/'

    # Checkout the python tools repo
    # -------------------------------------------      
    - name: checkout python tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'
     
    - uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
        
    - name: Installing dependencies
      run: |
        install.packages("remotes")
        install.packages("arrow", repos = c("https://apache.r-universe.dev", "https://cran.r-project.org"))
        remotes::install_github("Infectious-Disease-Modeling-Hubs/hubData", dependencies=TRUE)
        remotes::install_github("Infectious-Disease-Modeling-Hubs/hubEnsembles")
        install.packages("dplyr")
        install.packages("jsonlite")
        install.packages("optparse")
        install.packages("purrr")
      shell: Rscript {0}

    - name: Generate Ensemble
      id: generate_ensemble
      run: |
        # call R script from tools
        Rscript ./tools/R-code/generate-ensemble.R --hub_path "./repo" --agg_fun "median" --model_id "hubEnsemble" --team_id "respicast"

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Update ensemble data"
          default_author: github_actions
          push: true


  call-persisting-wf:
    needs: ensemble_job
    uses: european-modelling-hubs/flu-forecast-hub/.github/workflows/persist_changes.yml@main
    with:
      changes-list: ${{ needs.ensemble_job.outputs.changed_files }}

    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}     

    # Save changes to artifact for later persisting 
    # - name: Save changes to artifact
    #   env:
    #     changed_files: ${{ steps.generate_ensemble.outputs.ensemble_file }}
    #   run: |
    #     echo "{ \"pr-changes\" : \"$changed_files\" }" > pr_changes.json
          
    # - name: Upload changes
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: pr_changes
    #     path: ./pr_changes.json
