name: PersistChangesToJsonDB

on:
  workflow_call:
    
    inputs:
    
      # input list of changes is a blank separated string
      changes-list:
        required: true
        type: string

    secrets:
      # pass in the GITHUB_TOKEN    
      envPAT:
        required: true

  workflow_dispatch:

jobs:

  update_json_changes:    
    runs-on: ubuntu-latest
    steps:

    
      
    - name: Trace the changes
      run: | 
        echo "Changes: ${{ inputs.changes-list }}"


    # Checkout the python tools repo
    # used to authenticate and validate the PR
    # -------------------------------------------      
    - name: checkout python tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.envPAT }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'


    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.envPAT }}
        repository: 'european-modelling-hubs/flu-forecast-hub'
        ref: 'main'
        path: './repo/'


    
    # Store changes 
    # -------------------------
    - name: Store Changes 
      env:
        data: ${{ inputs.changes-list }}
      run: |
        python ./tools/code/persist-changes.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Update data storage"
          default_author: github_actions
          push: true
