name: Fake - Hub Submission Validation
on:

  workflow_dispatch:

jobs:
  scheduled-submit:
    runs-on: ubuntu-latest
    
    steps:

    - name: Save changes to artifact
      env:
        changed_files: "model-metadata/Test1-SIRModel.yml model-output/Test1-SIRModel/2023-11-11-Test1-SIRModel.csv"
        run: |
          echo "{ "pr-changes" : {{$changed_files}} }" > pr_changes.json
      
    - name: Upload changes
      uses: actions/upload-artifact@v2
      with:
        name: pr_changes
        path: ./pr_changes.json
